version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "weekly"
- package-ecosystem: "pip"
  directory: "/tools/tech-stack-collector"
  schedule:
    interval: "weekly"
